version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  printenv:
    docker:
      - image: cimg/python:3.12
    steps:
      - run:
          name: Printenvs
          command: |
            printenv

  lint-test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            flake8 --ignore=F821,E741,F821,E501,E501,F821,E501,E501,W292 --verbose app.py
      - run:
          name: Linting done
          command: echo "Linting done"
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            pytest || echo "No tests found."
      - run:
          name: Test Done
          command: echo "Test done."

  slack-notification:
    docker:
      - image: cimg/python:3.12
    steps:
      - run:
          name: slack-notification
          command: echo "Sending to slack"
      - run:
          name: slack-notification done
          command: echo "Notification done"

  waiter:
    docker:
      - image: cimg/python:3.12
    steps:
      - run: |
          while [[ $(curl --location --request GET "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/job" --header "Circle-Token: $CCI_Token"| jq -r '.items[]|select(.name != "waiter")|.status' | grep -c "running") -gt 0 ]]
            do
              sleep 1
            done
      - run: echo "All required jobs have now completed"

  pr-comment-fail:
    docker:
      - image: cimg/python:3.12
    steps:
      - run:
          name: Add Comment to PR
          command: |
            curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
            -d '{"body":"PR failed on this stage: ${CIRCLE_STAGE} - [Job link](${CIRCLE_BUILD_URL})"}' \
            https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues/${CIRCLE_PR_NUMBER}/comments

workflows:
  pr-workflow:
    jobs:
      - printenv
      - lint-test:
          requires:
            - printenv
      - test:
          filters:
            branches:
              only:
                - /.*/
              ignore:
                - main
                - dev
                - staging
          requires:
            - lint-test
      - slack-notification:
          filters:
            branches:
              only:
                - dev
                - staging
                - main
          requires:
            - test
      - waiter:
          requires:
            - slack-notification
      - pr-comment-fail:
          requires:
            - waiter