version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  printenv:
    docker:
      - image: cimg/python:3.12
    steps:
      - run:
          name: Printenvs
          command: |
            printenv

  lint-test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If your requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Run tests
          command: |
            if flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics | grep -q "0"; then
              echo "Lint has passed and ready to merge"
            else
              echo "Lint failed, fix the issues"
              exit 1
            fi
      - run:
          name: Linting done
          command: echo "Linting done"
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            pytest || echo "No tests found."
      - run:
          name: Test Done
          command: echo "Test done."

  pr-comment-fail:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Add Comment to PR
          command: |
            curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
            -d '{"body":"PR failed on this stage: ${CIRCLE_STAGE} - [Job link](${CIRCLE_BUILD_URL})"}' \
            https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues/${CIRCLE_PR_NUMBER}/comments
          when: on_fail

workflows:
  pr-workflow:
    jobs:
      - printenv
      - lint-test:
          filters:
            branches:
              only:
                - dev
                - staging
                - main
      - test:
          filters:
            branches:
              only:
                - dev
                - staging
                - main
          requires:
            - lint-test
      - pr-comment-fail:
          filters:
            branches:
              only:
                - dev
                - staging
                - main
          requires:
            - lint-test
            - test
